[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mmiat"
version = "0.1.0"

authors = [
    {name = "Milos Vujasinovic"}
]
requires-python = ">=3.8"
readme = "README.md"
dependencies = [
    "numpy",
    "torch"
]